### ISSUE TITLE
Lines starting with an object literal are hidden by mdbook

### ISSUE THREAD

**Issue by Sparkpin** [rune-rs/rune#10]
Lines in a code block starting with a hash (#) are hidden by mdbook, which is generally good for hiding lines that are irrelevant while still allowing doctests/playground runs to build. However, this clashes with Rune object literals, which also start with a hash. This can be seen in the last example of the [Pattern Matching](https://rune-rs.github.io/rune/pattern_matching.html) chapter.

The example displays as:
```rust
fn describe_car(car) {
    match car {
        _ => "Can't tell 😞",
    }
}

fn main() {
    println(describe_car(#{"model": "Ford", "make": 2000}));
    println(describe_car(#{"model": "Honda", "make": 1980}));
    println(describe_car(#{"model": "Volvo", "make": 1910}));
}
```
with the output
```
$> cargo run -- scripts/book/pattern_matching/fast_cars.rn
Pretty fast!
Can't tell 😞
What, where did you get that?
== () (5.3533ms)
```
...which doesn't make very much sense, until you view the source file:
```rust
fn describe_car(car) {
    match car {
        #{"make": year, ..} if year < 1950 => "What, where did you get that?",
        #{"model": "Ford", "make": year, ..} if year >= 2000 => "Pretty fast!",
        _ => "Can't tell 😞",
    }
}

fn main() {
    println(describe_car(#{"model": "Ford", "make": 2000}));
    println(describe_car(#{"model": "Honda", "make": 1980}));
    println(describe_car(#{"model": "Volvo", "make": 1910}));
}
```

**Comment by udoprog** [comment]
Thanks for spotting that!

I'm... not sure how to fix it. Maybe it's possible to disable by adding a [custom syntax](https://github.com/rust-lang/mdBook/issues/657)? Would be great if someone more familiar with mdbook could help out!

**Comment by Sparkpin** [comment]
mdBook itself has a [demonstration of the hash-hiding syntax](https://raw.githubusercontent.com/rust-lang/mdBook/master/book-example/src/format/mdbook.md) in their book, and they seem to use Bash highlighting to get around this issue. It's not a great fix, but it's at least a workaround.

**Comment by udoprog** [comment]
Thanks for the resources. Using a custom syntax seems to work.

Forked the `rust` language in `highlight.js` into the [`rune` branch of `rune-rs/rune`](https://github.com/rune-rs/highlight.js/tree/rune) and added instructions for how its built.
