### ISSUE TITLE
Allow using external objects containing references

### ISSUE THREAD

**Issue by sapir** [rune-rs/rune#166]
For example:

```rust
#[derive(runestick::Any, Default)]
struct MyObject<'a> {
    something: &'a u32,
}
```

Currently, `runestick::Any` requires `std::any::Any` which requires `'static`, and also `UnsafeFromValue` and `UnsafeToValue` require `'static`, so this is impossible. Also the derive macro doesn't handle the lifetime correctly.

It would be nice if this were allowed when not using async.

**Comment by udoprog** [comment]
This can't be supported, see discussion in #600
