### ISSUE TITLE
Unreferenced public imports are stripped

### ISSUE THREAD

**Issue by tgolsson** [rune-rs/rune#207]
e.g,

```rust
pub use other_file::do_something;

pub fn main() {
     do_something; // this line does nothing but if you remove it `do_something` won't be externally visible.
}
```

This requires one to create bogus references to all public functions; as in https://github.com/tgolsson/aoc-2020/blob/main/scripts/main.rn#L11.

I've noticed similar issues with module-private functions being marked as unused if the main function isn't called main, e.g.,
https://github.com/tgolsson/aoc-2020/blob/main/scripts/day1.rn#L3 `filter_inner` is marked as unused by the LSP.

**Comment by tgolsson** [comment]
@udoprog I'm happy with after your improvements, do you feel more work is needed or shall we close this? :-)

**Comment by udoprog** [comment]
Ah, yeah, this can be closed.
