### ISSUE TITLE
Add more detail to DebugInst and Diagnostics

### ISSUE THREAD

**Issue by tgolsson** [rune-rs/rune#225]
In order to provide good diagnostics it'd be helpful if the DebugInst not only pointed to the span of the *instruction* but also any related parts that are useful for diagnostics. For example, in a let binding it would make sense to have spans for all lhs elements as well as rhs. In a binary op, having the two operands would make sense. This can then be used to generate more detailed diagnostics with more exact spans for codespan-reporting.

**Comment by udoprog** [comment]
I believe this has been added. If a unit is provided and debug inst is available it adds richer diagnostics. The only question is additional work to improve it but that should happen piecemeal.
