### ISSUE TITLE
OOTB template literal are missing for bool

### ISSUE THREAD

**Issue by Roba1993** [rune-rs/rune#252]
There is no OOTB template literal implemented for the bool type.
This should be done in my opnion, because i64 etc. have an template literal.

**Comment by udoprog** [comment]
Hey!

So what do you mean with template literal, could you give an example?

**Comment by Roba1993** [comment]
Yes,

just check out the following code, this fails.
```
pub fn main() {
    let a = true;
    println(`${a}`);
}
```

this works.
```
pub fn main() {
    let a = 96;
    println(`${a}`);
}
```

**Comment by udoprog** [comment]
Ah. I see. Yeah, that would be useful!

For anyone who wants to take a stab at this, this is the code being invoked:
https://github.com/rune-rs/rune/blob/0.9.0/crates/runestick/src/vm.rs#L2230

In fact, it should be moved into `Value` and implemented like `string_debug` is, and possibly `bool` should just be another variant with a built-in implementation:
https://github.com/rune-rs/rune/blob/0.9.0/crates/runestick/src/value.rs#L290

Thanks for pointing it out!
