### ISSUE TITLE
How to call a function more than once?

### ISSUE THREAD

**Issue by pkolaczk** [rune-rs/rune#286]
I'd like to be able to call a function in Rune from Rust multiple times, as cheaply as possible.
I noticed `Vm::execute` and `Vm::call` take `self` by move, so it is not possible to reuse a vm after the call completed.
What is the idiomatic way to run a short function multiple times, with minimal FFI overhead?

**Comment by tgolsson** [comment]
VMs are cheap and you can just create more when you need them. The overhead is just function lookup + stack insertion. If you really want to optimize it you can:

* Extract `VM::set_entrypoint` to your code and cache the IP, saving the lookup
* Pass that to `VM::set_ip`
* Manually clear and then fill the stack using code from call/execute and `VM::stack_mut`

**Comment by udoprog** [comment]
Oh, talk about racy comment. Yours is better though!

**Comment by udoprog** [comment]
@pkolaczk set up #287 which when merged should allow for what you want without having to fuzz about too much.

**Comment by pkolaczk** [comment]
Thanks. Cloning works indeed and it is reasonably fast. 

I tried to go the way @tgolsson suggested, but then after setting the IP, I don't really know how to execute. Internally it calls `into_execution` but that's private, as well as `VmExecution`. 

Now trying #287...

**Comment by pkolaczk** [comment]
Ok, #287 also works, but there isn't any perf difference. So you were right cloning the vm is fast.

**Comment by pkolaczk** [comment]
BTW: I must say now it looks like it is already faster than `mlua`. Very promising.

**Comment by udoprog** [comment]
> Any way to also officially cache the function lookup?

Not as it stands, but you can calculate the function hash up front as it's done here:
https://github.com/rune-rs/rune/blob/main/benches/benches/fib.rs#L50

The rest of the work involves looking up the offset in a map, so in a sense it's already cached. But we could in theory add more low-level functions to give someone more control. See `set_entrypoint` if that is something you'd want to work on:
https://github.com/rune-rs/rune/blob/83e9c45443930dce79b894323828a658385c36c5/crates/runestick/src/vm.rs#L346

**Comment by tgolsson** [comment]
> Thanks. Cloning works indeed and it is reasonably fast.
> 
> I tried to go the way @tgolsson suggested, but then after setting the IP, I don't really know how to execute. Internally it calls `into_execution` but that's private, as well as `VmExecution`.
> 
> Now trying #287...

I'll see if I can remember this tonight and check how I did.
