### ISSUE TITLE
How to pass an external Rust struct into a Rune function?

### ISSUE THREAD

**Issue by pkolaczk** [rune-rs/rune#288]
I have a struct that wraps a reference to a database connection like this:

```rust
#[derive(Any)]
struct Session {
  inner: Arc<InnerSession>
}
```

`InnerSession` is out of my control, but it is Send + Sync.
I wanted to expose that in the Rune script, without too much copying / cloning.
So I wrapped it in `Shared`.

But when I try to pass a `Shared<Session>` as arg, I'm  getting:
```
the trait `runestick::Any` is not implemented for `runestick::Shared<rune_executor::Session>`
```

How to do it properly?

**Comment by pkolaczk** [comment]
I got something that compiles - if I just pass a `Session` without wrapping it into `Shared`, it works (but then I have to just clone it every time). However that requires a possibly more costly Arc clone:

```
self.vm.execute(self.init_fn, (self.session.clone(),))?
```

Any ideas how to do it idiomatically?

**Comment by tgolsson** [comment]
You can pass ref/mut if you use `Vm::call` If you look at the docs [here](https://docs.rs/runestick/0.9.1/runestick/struct.Vm.html#method.execute) and compare that to [`Vm::call`](https://docs.rs/runestick/0.9.1/runestick/struct.Vm.html#method.call), the latter takes `GuardedArgs`. That works with refs, while `Vm::execute` takes Args, which requires ownership.

**Comment by pkolaczk** [comment]
That works. One more question - is it possible to actually pass it as a global variable instead of as a parameter?

**Comment by tgolsson** [comment]
Not to pass it, at least as far as I'm aware. You can bind Rust constants and functions to be globally accessible, which might work:

```rust
fn on_call() {
    let session = context::get_current_session(); // We set this on Rust caller side, maybe using thread-local variables.
}
```

**Comment by pkolaczk** [comment]
Ok, thank you.
