### ISSUE TITLE
How to convert the return value into a STRING_DISPLAY string?

### ISSUE THREAD

**Issue by pkolaczk** [rune-rs/rune#290]
I'm calling a Rune function from Rust. That function can return an `Err(CassError)`, where `CassError` is an external type that implements the `STRING_DISPLAY` protocol.

Dumping that error object from inside of the script works fine:

```rust
pub async fn init(db) {
    let prep_result = db.prepare("insert", "a broken query").await;
    if let Err(e) = prep_result {
        dbg(`Error ${e}`);
    }
    prep_result
}
```

Then I try to print the `Value` I obtained from the call, and indeed it is a proper `Err` but after unwrapping I get only `Any(CassError)` description instead of the fully formatted object. 

```
"Error Cassandra detailed error SERVER_INVALID_QUERY: Invalid INTEGER constant (1) for \"id\" of type text"
error: Failed to initialize: Function init returned error: Any("CassError")
```

How do I get the formatted object outside of the vm? I tried the `string_display` method naively, hoping the docs is wrong, but it was right and it doesn't work outside of the vm :(

The source of `CassError` if that helps:
```rust
#[derive(Any, Debug)]
pub struct CassError {
    #[rune(get)]
    msg: String,
}

impl CassError {
    fn display(&self, buf: &mut String) -> std::fmt::Result {
        use std::fmt::Write;
        write!(buf, "{}", self.msg)
    }
}

impl Display for CassError {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.msg)
    }
}

impl std::error::Error for CassError {}

```

**Comment by udoprog** [comment]
If I'm understanding you correctly: If you want the string out of the Vm, you can use `format!("{}", e)` which will invoke STRING_DISPLAY to format `e` and return it as a string. But you could also directly return the error out and call its native `fmt::Display` implementation in Rust since it implements `Any`.

**Comment by pkolaczk** [comment]
This was my first attempt to format it normally, but no:
```
163 |                     format!("{}", e),
    |                                   ^ `runestick::Value` cannot be formatted with the default formatter
```

The problem is I don't exactly control the type of the value returned, however I'd like to convert it to the best string representation - if the value implements STRING_DISPLAY, then I'd like to get that; and a debug string otherwise.

**Comment by udoprog** [comment]
Ah. So you'll want to decode the value (e.g. `let e = CassError::from_value(e)?`). But also, `Value` has a helper method to invoke the display protocol if that is the only thing you want to do:
https://docs.rs/runestick/0.9.1/runestick/enum.Value.html#method.string_display

**Comment by udoprog** [comment]
I noticed that with `Value::string_display` you also need to provide a `Vm`, I'm gonna check if that's possible through public API right now.

**Comment by pkolaczk** [comment]
I tried to use `string_display` but the documentation says:
```
Note that this function will always failed if called outside of a virtual machine.
```

**Comment by pkolaczk** [comment]
So decoding with `from_value` works fine but this is not very generic as it covers only the types I know of.
It wouldn't work if the writer of my extension script defined their own error struct and returned that to the host program.

**Comment by udoprog** [comment]
Yeah. it's currently not possible to call this function! I'm adding a helper method to `Vm` to make it possible.

**Comment by pkolaczk** [comment]
Fortunately with the recent changes that allow to reuse the vm, I have a reference to vm ;)

BTW: Thank you for all the work you put into this project. It is really awesome and it will raise my benchmarking tool (also open-source) for Cassandra to a totally new flexibility level. And rune is actually really fast - I'm impressed because I'm getting better performance of it than from mlua I used before.

**Comment by udoprog** [comment]
I'm glad to hear it, and thanks for using Rune! Feedback from real projects using it helps to push things a lot.
