### ISSUE TITLE
Parameterizing scripts

### ISSUE THREAD

**Issue by pkolaczk** [rune-rs/rune#294]
I was wondering how to allow users of my program to parameterize their extension scripts. 
The most natural way would be to use constants.
They make it easy to list all parameters at the top, so whoever uses the script could easily change their values.

```rust
const PARAM = 100;

fn main() {
  // code using a constant
  println(`${PARAM}`);
}
```

However, I'd also like to be able to override the values form the command-line parameters of the host program that loads the script. Unfortunately it turns out that constants in the Rune source code take precedence over the constants registered in the context, so the host program cannot override the constant value. 

Hence I was thinkng that maybe something like that would be possible:

```rust
const PARAM = get_int_option("param", 100);

fn main() {
  // code using a constant
  println(`${PARAM}`);
}
```

Where `get_int_option` would just return the CLI parameter value or the default value, if the option was not given.
But it looks like I can't initialize a constant with a value returned from a function - it just says the function is missing, despite me registering it in the context. 

Is there any way to override the constant value from the Rust program that compiles the script (e.g. during compile time by just changing the const value or better by providing a function that fetches config parameter)?

**Comment by pkolaczk** [comment]
I think I'm almost there - I noticed I can use macros on the RHS of the const assignment. 
So I'm now aiming at the following:

```rust
const PARAM = get_int_option!("param", 100);
```

However, I've hit another problem - the `Module::_macro` needs a function that is `Copy + Sync + Send`, which makes it virtually impossible to associate any more complex data with it. I need to pass a `HashMap` with options to the macro procedure. Could you relax it at least to make it need `Clone` instead of `Copy`? In that case I could at least use `Arc`.

**Comment by udoprog** [comment]
If the constraint is not needed, then feel free to drop it. But I'd also be fine with allowing function calls in a constant context (which will memorize the result even if the fn isn't constant). It just isn't implemented yet.

This is where function calls in const contexts are currently handled:
https://github.com/rune-rs/rune/blob/331ba71f8faeb502f1c58d31c9696ffa4438abdb/crates/rune/src/ir/ir_interpreter.rs#L147

**Comment by pkolaczk** [comment]
#295

**Comment by pkolaczk** [comment]
> But I'd also be fine with allowing function calls in a constant context (which will memorize the result even if the fn isn't constant). It just isn't implemented yet.

Oh, definitely. But that minor change from `Copy` to `Clone` unblocks me now.
