### ISSUE TITLE
How to parse macro argments, separated by commas?

### ISSUE THREAD

**Issue by pkolaczk** [rune-rs/rune#299]
I'm processing a stream of tokens in a macro context and I expect the next token to be a comma.

```rust
let comma = parser.parse::<what goes here?>()?;
```

I couldn't find a type for comma.

**Comment by udoprog** [comment]
What goes there is something implementing `Parse`. Here's an example of it:
https://github.com/rune-rs/rune/blob/main/crates/rune/src/macros/format_args.rs#L109

The `T!` macro expands to a token (which also implements `Parse`) matching the given argument. The exact token for commas happen to be `rune::ast::generated::Comma` (see https://docs.rs/rune/0.9.1/rune/ast/generated/index.html and https://docs.rs/rune/0.9.1/rune/macro.T.html).

It's defined in https://github.com/rune-rs/rune/blob/main/assets/tokens.yaml and code generation for it is implemented in https://github.com/rune-rs/rune/blob/main/tools/generate/src/main.rs#L174

**Comment by pkolaczk** [comment]
Thanks! That was it. I was looking under `rune::ast` and that's why I couldn't find it. 

BTW: Backticks are missing in the first part of the message in:
```
   #[error("expected {expected}, but got `{actual}`")]
    Expected {
        actual: &'static str,
        expected: &'static str,
    },
```

**Comment by pkolaczk** [comment]
Or maybe not...

That message doesn't look right.

```
3 │ const FOO = param!("foo" | 3);
  │                          ^ expected ,, but got `|`
```

But on the flipside this is ok:

```
3 │ const FOO = param!("foo", );
  │                          ^ expected expression, but got `eof`
```

**Comment by udoprog** [comment]
Yeah, the `Expected` errors could be improved depending on what is being expected. A punctuation require back ticks to be legible while a description doesn't.
