### ISSUE TITLE
Importing macros by `use` doesn't work

### ISSUE THREAD

**Issue by pkolaczk** [rune-rs/rune#324]
I registered a macro `param` in crate `latte`:

```rust
        let mut latte_module = Module::with_crate("latte");
        latte_module
            .macro_(&["param"], move |ctx, ts| context::param(ctx, &params, ts))
            .unwrap();
```

Then I can access that macro in the rune source by using fully qualified name:

```rust
const FOO = latte::param!("foo", 100);
``` 

However this results in the compile error:
```rust
use latte::*;
const FOO = param!("foo", 100);  // not found: param!
```
```rust
use latte::param;
const FOO = param!("foo", 100);  // not found: param!
```

And the following code causes Rune compiler to fall into an infinite loop:
```rust
use ::latte::param;
const FOO = param!("foo", 100);  
```

**Comment by udoprog** [comment]
Well that's not good. Thanks for the report!

This is clearly a bug, but I think you can get through it by using `Module::with_item` for now instead of the (apparently) under-tested crate resolution it'd use with `Module::with_crate`.

**Comment by udoprog** [comment]
It seems like the immediate issue with crate resolution has been fixed (or at least according to my testing). Closing this for now!
