### ISSUE TITLE
Instance Functions on Template Literals Fail

### ISSUE THREAD

**Issue by Steven0351** [rune-rs/rune#326]
Environment
* Arch Linux - Kernel 5.15.2
* Rust 1.56.1 - 2021 Edition
* Rune 0.10.0 (main branch) - commit fcf3fddccb8e87b9ebe24f0114625d8471e52e4d (latest commit as of a few days ago)

I've been evaluating Rune for a project I'm currently in the exploratory phase for and I came across an interesting issue. Given the following function being added to the runtime as an instance function:
```rust
fn trim_indent(string: String) -> String {
    string
        .lines()
        .map(|s| s.trim_start())
        .collect::<Vec<&str>>()
        .join("\n")
}
```
when trying to invoke it directly on a template literal it fails at runtime:
```rust
let template_runtime_failure = 
    `Hello, I am ${age} years old.
     How old are you?`.trim_indent();
```
However, after calling the function on it after initial assignment it behaves as expected:
```rust
let template_runtime_sucess = 
    `Hello, I am ${age} years old.
     How old are you?`;

let template_runtime_success = template_runtime_success.trim_indent();
```
I would  assume that any custom instance functions that would work on String would also work on template literals as  they do in Javascript. I'm guessing the runtime failure is due to the method being called on the template literal before it is evaluated.

Here is a full example for reproduction purposes:
```rust
use rune::{ContextError, Diagnostics, Module, Source, Sources, Vm};
use std::sync::Arc;

fn main() -> rune::Result<()> {
    let mut context = rune_modules::default_context()?;
    context.install(&trim_module()?)?;

    let runtime = Arc::new(context.runtime());

    let mut sources = Sources::new();
    sources.insert(Source::new(
        "script",
        r#"
        pub fn test_multiline_template() {
            let age = 35;
            
            let template_runtime_failure = 
                `Hello, I am ${age} years old.
                  How old are you?`.trim_indent();

            println(template_runtime_failure);
        }
        "#,
    ));

    let mut diagnostics = Diagnostics::new();
    
    let result = rune::prepare(&mut sources)
        .with_context(&context)
        .with_diagnostics(&mut diagnostics)
        .build();

    let unit = result?;
    let mut vm = Vm::new(runtime, Arc::new(unit));

    vm.call(&["test_multiline_template"], ())?;

    Ok(())
}

fn trim_module() -> Result<Module, ContextError> {
    let mut m = Module::with_item(&["mymodule"]);
    m.inst_fn("trim_indent", trim_indent)?;
    Ok(m)
}

fn trim_indent(string: String) -> String {
    string
        .lines()
        .map(|s| s.trim_start())
        .collect::<Vec<&str>>()
        .join("\n")
}
```

**Comment by udoprog** [comment]
So the bug is that the template literal desugars to:

```rust
#[builtin(literal)] template!("Hello, I am " , age , " years old. How old are you?").trim_indent();
```

And therefore `#[builtin(literal)]` applies to the instance call expression rather than the `template!` macro. A solution would be to ensure that the template literal desugars to an expression group. Either a hidden or a literal one.

Essentially this:

```rust
(#[builtin(literal)] template!("Hello, I am " , age , " years old. How old are you?")).trim_indent();
```
