### ISSUE TITLE
Passing an interpolated string from Rune script to a Rust function passes garbage

### ISSUE THREAD

**Issue by pkolaczk** [rune-rs/rune#344]
I've got a Rune script:

```rust
const KEYSPACE = "latte";
const TABLE = "basic";

pub async fn schema(db) {
    db.execute(`CREATE KEYSPACE IF NOT EXISTS ${KEYSPACE} \
                    WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 }`).await?;
    db.execute(`CREATE TABLE IF NOT EXISTS ${KEYSPACE}.${TABLE}(id bigint PRIMARY KEY)`).await?;
}

pub async fn erase(db) {
    println(`TRUNCATE TABLE ${KEYSPACE}.${TABLE}`);
    db.execute(`TRUNCATE TABLE ${KEYSPACE}.${TABLE}`).await
}
```

The execute instance function looks like this:

```rust
impl Session {
pub async fn execute(&self, cql: &str) -> Result<(), CassError> {
        println!("Executing: {}", cql);
        let statement = Statement::new(cql, 0);
        let start_time = self.stats.borrow_mut().start_request();
        let rs = self.inner.execute(&statement).await;
        let duration = Instant::now() - start_time;
        self.stats.borrow_mut().complete_request(duration, &rs);
        rs?;
        Ok(())
    }
}
```

and is registered this way:

```rust
 let mut session_module = Module::default();
        session_module.ty::<Session>().unwrap();
        session_module
            .async_inst_fn("execute", Session::execute)
            .unwrap();
```

Now, when I run this on Rune until commit 5fcf6e19bed6d5670aa2f2bfebfdadab120bccef, everything is fine and I'm getting:

```
info: Creating schema...
Executing: CREATE KEYSPACE IF NOT EXISTS latte WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 }
Executing: CREATE TABLE IF NOT EXISTS latte.basic(id bigint PRIMARY KEY)
info: Erasing data...
TRUNCATE TABLE latte.basic
Executing: TRUNCATE TABLE latte.basic
```

However since commit 0fca7d6db68ee64486247d5b4c8cc1050567e9a3 the string passed to execute becomes garbage:

```
info: Creating schema...
Executing: CREATE KEYSPACE IF NOT EXISTS latte WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 }
Executing: CREATE TABLE IF NOT EXISTS latte.basic(id bigint PRIMARY KEY)
info: Erasing data...
TRUNCATE TABLE latte.basic
Executing: ��
```

And this happens always in the call to `erase`, not call to `schema`. 
The garbage passed to execute is different each time. 
Reproduces always, both in debug and release mode.

If I replace string interpolation with a non-interpolated string (non template) all works fine (except it doesn't do what I want). 

On the Rust side, `Vm` is created fresh for each call, however it shares the `Context` and the `Unit` (only Arc ref is cloned).

**Comment by udoprog** [comment]
Great find!

So this would be the offending line:
https://github.com/rune-rs/rune/commit/0fca7d6db68ee64486247d5b4c8cc1050567e9a3#diff-0c52f6f0e52450b690dbc71ce1752bd2c3d87bbd7c3c61ec1c28330036fa5d85R870

The issue here is that `$var.0` contains "stack guards", which has to be preserved for the duration of the future as per [UnsafeFromValue::Guard](https://github.com/rune-rs/rune/blob/main/crates/rune/src/runtime/from_value.rs#L57).

I also suspect the 2021 edition would have independently caused this issue even without 0fca7d6db68ee64486247d5b4c8cc1050567e9a3 because of the new [Disjoint Capture in Closure](https://doc.rust-lang.org/edition-guide/rust-2021/disjoint-capture-in-closures.html) assuming it applies to `async` blocks.

**Comment by udoprog** [comment]
@pkolaczk any chance you can check that things work for you after #345?

**Comment by pkolaczk** [comment]
Just checked it, works flawlessly! Thank you.

**Comment by udoprog** [comment]
Thank you!
