### ISSUE TITLE
yanked futures-core 0.3.18

### ISSUE THREAD

**Issue by d00z3l** [rune-rs/rune#372]
Hello,

Rune looks very interesting, I am trying to test it out but can't download it as it depends on a yanked version of futures-core. Are you able to release another version?

```
error: failed to select a version for the requirement `futures-core = "^0.3.18"`
candidate versions found which didn't match: 0.3.17, 0.3.16, 0.3.15, ...
location searched: crates.io index
```

**Comment by udoprog** [comment]
Release 0.10.3 which reduces the dependency on futures-*. Please take it for a spin!

**Comment by d00z3l** [comment]
Thanks, it is now compiling!
