### ISSUE TITLE
Can't parse float number in JSON

### ISSUE THREAD

**Issue by twigly** [rune-rs/rune#377]
Hi Rune Team,

The `Value` enum has a `Float` variant [here](https://github.com/rune-rs/rune/blob/main/crates/rune/src/runtime/value.rs#L235).
But there is no `visit_f32` and `visit_f64` methods in the `Visitor` trait implementation ([here](https://github.com/rune-rs/rune/blob/main/crates/rune/src/runtime/value.rs#L1361)).

As a result, it's not possible to parse JSON containing float numbers. The program panics on the the following error:
`"invalid type: floating point '2.1', expected any valid value"`

I'm happy to fix the issue if you like.

**Comment by udoprog** [comment]
Nice find! This should be fixed.
