### ISSUE TITLE
The INDEX_SET protocol fn now expects a unit return

### ISSUE THREAD

**Issue by jrobsonchase** [rune-rs/rune#390]
I updated to `main` to take advantage of the new enum goodies, and this broke unexpectedly.

Using a previously-accepted function that returns an `Option` as the `INDEX_SET` function now causes a vm error: 
```
Error: expected `unit`, but found `Option`
```

This is currently broken in the implementation of `HashMap` in `crates/rune/src/modules/collections.rs`. Also opening a PR adding a test case illustrating the failure.

**Comment by udoprog** [comment]
I'll triage this properly when I get back home. But for now, INDEX_SET should probably require that a unit is returned unless there's a good reason not to. But that would mean a major version bump since the protocol is more restrictive.
