### ISSUE TITLE
Allow variable names starting with an underscore `_`

### ISSUE THREAD

**Issue by SWW13** [rune-rs/rune#435]
It's sometimes useful to name variables starting with an underscore, e.g.: to temporarily silence unused warnings, prefix a numeric variable name or reflect a variable name from other source code.

I think it's fine to go with Rusts approach of only `_` being the "drop immediately" special case and other variables starting with `_` just silencing the unused warning (not sure if Rune has that already).

```rune
error: parse error
  ┌─ test.rn:2:8
  │
2 │   let _test = 0;
  │        ^^^^ expected `=`, but got ident

Error: failed to build rune sources (see diagnostics for details)
```

**Comment by udoprog** [comment]
Thanks. Should be relatively simple lexer fix!
