### ISSUE TITLE
VSCode, commenting out lines not working

### ISSUE THREAD

**Issue by jakubtyrcha** [rune-rs/rune#438]
Repro:
1) Open a .rn file with extension installed.
2) Try to comment out code using `Toggle line comment` or `Toggle block comment` from `Edit` menu, or the shortcut equivalent.
3) Lines will not be commented out, unlike with other languages.

**Comment by udoprog** [comment]
Thanks!

**Comment by udoprog** [comment]
This is fixed in the latest editor extension.
