### ISSUE TITLE
REPL and IDE support for Rune

### ISSUE THREAD

**Issue by cianoc** [rune-rs/rune#44]
Do you have any plans to implement a REPL for Rune, or a language server?

What I'd like for my personal projects is to be able to ship a binary that contains a REPL for the project (in this instance a MIDI programming environment for livecoding), and a language server that can be used with VSCode/Emacs/VIM, etc. Maybe something like a Rune-Repl crate and a Rune-RLS crate (naming is hard).

More than happy to experiment with this on my own and see what I end up with, but wasn't sure if you had something in mind, or if there was code that I had missed, or if you had different ideas about this?

Awesome project btw. Very impressed with what you've done so far, and I really like the focus of this project.

**Comment by udoprog** [comment]
A language server is coming. The compiler [is designed in a way to make this easier](https://rune-rs.github.io/rune/compiler_guide.html).

A language server would perform the first step unconditionally on source changes (indexing), and then make use of the query system to figure out what various items are.

Stay tuned!

**Comment by udoprog** [comment]
I will note that repl support is not planned, and the compilation / lowering model doesn't allow for it.

**Comment by niclashoyer** [comment]
@udoprog @cianoc just stumbled on this after wanting to quickly try out rune. While not technically a REPL, I've put something together to simulate kind of a REPL. The input is recompiled after each input: https://github.com/niclashoyer/rune-repl
