### ISSUE TITLE
FileSourceLoader going up one directory to look for script file?

### ISSUE THREAD

**Issue by Rawieo** [rune-rs/rune#443]
Could it be that because of [this pop](https://github.com/rune-rs/rune/blob/2d86f90a3725c5962e9fa334510ea4a5859f2452/crates/rune/src/compile/source_loader.rs#L28) FileSourceLoader ignores the last item in the `root` path?

I made a "scripts" directory in my project, then joined it to manifest directory path (`manifest_dir.join("scripts")`) but it seemed to search for the script file in the manifest directory still. I joined another "fictitious" path and it seems as thought it helped.

Or is it intentional?

```rust
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let context = rune_modules::default_context()?;
    let mut sources = rune::Sources::new();
    let scripts_path = manifest_dir.join("scripts").join("_");
    let mut loader = FileSourceLoader::new();
    let main_item = Item::with_item(&["main"]);
    let source = loader.load(&scripts_path, &main_item, Span::empty())?;
    sources.insert(source);
```

**Comment by udoprog** [comment]
🤔 `FileSourceLoader` should be looking for files relative to some current file. I.e. when you insert a file to be compiled in a collection of `Sources` you have to specify the full path to the source file and the loader would try and load any imports relative to that (non-directory) path.

**Comment by Rawieo** [comment]
Ok, thank you very much, that makes sense.
