### ISSUE TITLE
Community Site for Rune

### ISSUE THREAD

**Issue by cianoc** [rune-rs/rune#45]
Is there a community site for Rune such as a discord, or reddit?

**Comment by udoprog** [comment]
Note a site, but I'm using a channel in my Discord to coordinate right now:
https://discord.gg/v5AeNkT

If there's a lot of interest I might create a dedicated one.

**Comment by udoprog** [comment]
A site is up on https://rune-rs.github.io now. It's pretty bare bones with links (and upcoming posts!). But the basic plumbing is up and running.
