### ISSUE TITLE
How to retrieve AST of scripts?

### ISSUE THREAD

**Issue by jasal82** [rune-rs/rune#450]
How do I retrieve the AST of loaded sources for further processing? Specifically, I want to query the list of functions with a certain signature. There's no information about that in the docs and I can't figure it out from the code, although I'm sure there must be a way.

**Comment by udoprog** [comment]
AST is not publicly visible, but if you're looking for functions recommend you use a `CompileVisitor` which is called for every meta item being visited, that includes functions.

[Example use in rune-cli to gather test function](https://github.com/rune-rs/rune/blob/16a470ffe78219c283e60bf2874327c3598b3f61/crates/rune-cli/src/check.rs#L43). And [this is the implementation of the `CompileVisitor` itself](https://github.com/rune-rs/rune/blob/16a470ffe78219c283e60bf2874327c3598b3f61/crates/rune-cli/src/visitor.rs#L36).

Once you have those, you can use the hash to lookup the function from the compiled `Unit`:
<https://docs.rs/rune/latest/rune/runtime/struct.Unit.html#method.function>.

It's worth noting that the only relevant parts of a functions signature is the number of arguments and its hash. All other information is erased at compile time (by default), all though some more information can be enabled and maybe expanded on [with debuginfo](https://docs.rs/rune/latest/rune/runtime/struct.Unit.html#method.debug_info) which is [enabled in build options](https://docs.rs/rune/latest/rune/compile/struct.Options.html#method.debug_info).

I hope this helps!

**Comment by jasal82** [comment]
Yes, thank you very much, that helps. Two follow-up questions: Is there a plan to keep this kind of metadata at runtime? This could also be used to implement reflection mechanisms. And further, I'd be interested to know if it's possible to publish a Rust function to Rune that allows Rune functions to be registered (in a Vec or HashMap) for later execution in the VM context.

**Comment by udoprog** [comment]
Yes, I believe the type you're looking for is `Function` or `SyncFunction` if you need it to be `Send`.

In Rune, free functions and closures can be converted to this.

**Comment by jasal82** [comment]
Great, thanks a lot. I got everything working now.
