### ISSUE TITLE
Support for getting the value of a constant

### ISSUE THREAD

**Issue by vars1ty** [rune-rs/rune#451]
Perhaps adding support for getting the value of a constant could be useful? Something like:
```rust
pub fn main() {
    vm.lookup_constant(...);
    ...
}
```

Since right now I have to use functions that return a value, when simply using a constant would be much more ideal.

**Comment by udoprog** [comment]
Hey!

You can do that with [`Unit::constant`](https://docs.rs/rune/latest/rune/runtime/struct.Unit.html#method.constant), or iterate over constants with [`Unit::iter_constants`](https://docs.rs/rune/latest/rune/runtime/struct.Unit.html#method.iter_constants) since that's where they are stored.

**Comment by udoprog** [comment]
Oh, and there's also [constants in the runtime context](https://docs.rs/rune/latest/rune/runtime/struct.RuntimeContext.html) if that's something you're looking for.

**Comment by udoprog** [comment]
Glad to hear it!
