### ISSUE TITLE
0.12.2 release did not get completed

### ISSUE THREAD

**Issue by chenrui333** [rune-rs/rune#453]
👋 it looks like the 0.12.2 release did not get completed ([action run failed](https://github.com/rune-rs/rune/actions/runs/4489856182/jobs/7896202901)), create this issue to raise some awareness! Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/126348

**Comment by udoprog** [comment]
Hi!

That build is not a blocker, but rather it's an optional one which runs benchmarks. I've set up a release on Github since that seems to be what you need.

Please re-open if there's anything else!
