### ISSUE TITLE
[Tooling] IDE Syntax highlighting

### ISSUE THREAD

**Issue by shekohex** [rune-rs/rune#46]
Rune Syntax is almost the same as Rust syntax (without types) we could use the same Rust Syntax highlighting for VSCode [here](https://github.com/dunstontc/vscode-rust-syntax).

I could start working on that after finishing what I missed at #35 

Related to #44

**Comment by udoprog** [comment]
You can also find the grammar for Rust used in rust-analyzer here: https://github.com/rust-analyzer/rust-analyzer/tree/master/editors/code

But yeah, writing and publishing a vscode module will be the way to get it done.

**Comment by udoprog** [comment]
I decided to set up something basic since there were a number of steps which would be difficult for others to do. Namely setting up a logo and publishing.

A basic plugin is now up at: https://marketplace.visualstudio.com/items?itemName=udoprog.rune-vscode
