### ISSUE TITLE
Proper way to call Rust from Rune Scripts

### ISSUE THREAD

**Issue by felipetesc** [rune-rs/rune#486]
Hello. Before writing this post I searched the book about it and all I found was how to call Rune from the Rust language, but I didn't find a way to call Rust libraries from Rune. Maybe that's not possible, or I missed some information while reading the book, or you just haven't implemented this until now. I was wondering how we can create Rust modules to be called from Rune without changing Rune's own source code by adding new features. It would be very interesting if you could guide us how to create new plugins correctly. If you provide an example we will be grateful.

Thanks for Rune

**Comment by udoprog** [comment]
Hi!

This is how you do it:
https://github.com/rune-rs/rune/blob/main/examples/examples/native_function.rs#L45

Many more examples of native bindings are available in `rune_modules`:
https://github.com/rune-rs/rune/tree/main/crates/rune-modules/src
