### ISSUE TITLE
Language server should return `id` for unhandled requests

### ISSUE THREAD

**Issue by tgolsson** [rune-rs/rune#487]
This'd make it easier to handle failed requests as a client when using async. Right now it's hard to close the loop between a future waiting for a response with a log notification if it failed. 

I can't find anything in the LSP specification (v3.17) that specifies whether one approach or another; I just think it'd be "easier". The JSON-RPC 2.0 spec does suggest it should be the following format:

```
rpc call of non-existent method:

--> {"jsonrpc": "2.0", "method": "foobar", "id": "1"}
<-- {"jsonrpc": "2.0", "error": {"code": -32601, "message": "Method not found"}, "id": "1"}
```

**Comment by udoprog** [comment]
Out of curiosity, what would you be using this for in practice right now?

**Comment by tgolsson** [comment]
Haha, fair question. I'm figured I need *one more* side project so I'm building my own emacsy editor where I want to eventually use Rune as a plugin language! And of course the best way to get to that point is to make sure Rune has a nice developer experience - so it's my test bed for building my own LSP client.

**Comment by tgolsson** [comment]
This seems to work as expected; closing! Thanks again :-)
