### ISSUE TITLE
Support modules

### ISSUE THREAD

**Issue by udoprog** [rune-rs/rune#5]
Most of the infrastructure for this was added today. We now need the indexing stage to queue up modules to be parsed and indexed.

* [x] Basic implementation loading from the filesystem.
* [x] Implement visibility rules.
* ~~[ ] Make filesystem loading optional (through a setting in `Options`).~~

**Comment by dillonhicks** [comment]
With respect to visibility rules, how closely did you want to emulate Rust? How did you imagine the syntax and rules work?

I implemented a version of parsing visibility levels that I think has parity with rust's syntax. Like for #83 / #43 I disabled the feature in the compiler:

https://github.com/dillonhicks/rune/commit/ce93ae782b45548f29f847a4e1eb1e1421a13316

**Comment by udoprog** [comment]
> With respect to visibility rules, how closely did you want to emulate Rust? How did you imagine the syntax and rules work?

As close as possible. The things from the top of my head are:
* Currently any top-level items are queued up for compilation. This should be restricted to only include pub items: [this happens during indexing](https://github.com/rune-rs/rune/blob/3e159db515cfa34718b28a8976234089bdac5673/crates/rune/src/index.rs#L202).
* Items which are not exported at the root of a compilation should be mangled so that they are not addressable (easily) externally by prefixing them with [a new component](https://github.com/rune-rs/rune/blob/3e159db515cfa34718b28a8976234089bdac5673/crates/runestick/src/item.rs#L262). Re-exporting could be implemented by adding additional type hashes to the unit appropriate for their re-exported paths to make them addressable. i.e. `nested::$priv::name` and `name`.
* Most other rules should be enforceable at compile time. The entrypoint of a compilation can be treated as a crate root when resolving a path, [available here](https://github.com/rune-rs/rune/blob/3e159db515cfa34718b28a8976234089bdac5673/crates/rune/src/index.rs#L21).

**Comment by dillonhicks** [comment]
Thanks for the details. I am going to submit the PR for the parser soon and try tackling the compiler this week.
