### ISSUE TITLE
Allow to "implement" `?` via new `Protocol::TRY`

### ISSUE THREAD

**Issue by ModProg** [rune-rs/rune#541]
I suppose the rust std calls the function [`branch`](https://doc.rust-lang.org/std/ops/trait.Try.html#tymethod.branch) but without the context of the trait that might not the most speaking name :D.

**Comment by ModProg** [comment]
Not sure how this would be best implemented, as it would either require a new [`Value::ControlFlow`](https://doc.rust-lang.org/std/ops/enum.ControlFlow.html) or our `branch` would return a `Result` instead.

**Comment by ModProg** [comment]
I'd like to implement this, would you agree to use `Result` as the return type? and `try` for the name?

And how does one get the hash for the built_in functions?

**Comment by udoprog** [comment]
> And how does one get the hash for the built_in functions?

The hash for the protocols? They're just randomly generated:

```sh
cargo run --bin rune -- hash --random
```

**Comment by udoprog** [comment]
Seems like this is closed in #544
