### ISSUE TITLE
Detect when a VmExecution has finished (using step)

### ISSUE THREAD

**Issue by therealbnut** [rune-rs/rune#547]
Hey,

I'm trying to work out how to tell if execution has halted when using `VmExecution::step`.

I was using `VmErrorKind::IpOutOfBounds` to do this, but it's [now private](https://github.com/rune-rs/rune/pull/484) on `main`, so will stop working soon.

I also tried to copy the relevant part of `VmExecution::step`, but at least `run` and `call` were private:
```rust
vm_try!(budget::with(1, || Self::run(vm)).call())
```

---

Would it make sense to have a method on `VmError` like `is_halted(&self) -> bool` or something similar? For my specific case I'd need to check for `VmErrorKind::IpOutOfBounds` instead of `VmErrorKind::Halted` though.

I think the intention by making `VmErrorKind` private was to hide implementation details of the `Vm` that were exposed through its errors, and to help make the API more stable. I think at least some of these errors may have been useful though.

Thanks!

**Comment by therealbnut** [comment]
I forgot to mention, I've also checked if there's a way to check if the `ip` in the error is valid in the current `Unit`, but all `instruction` accessors also seem to be private now. I can perhaps use `DebugInfo::instruction_at` but that seems a bit fragile, and relies on having `DebugInfo`.

**Comment by therealbnut** [comment]
Sorry, I might need to sleep some more... I think I can just use `VmResult::Ok(Some(Value::Unit))` to detect halt.

**Comment by udoprog** [comment]
Glad you figured it out! If there's any other questions, feel free to join the Discord!

**Comment by therealbnut** [comment]
@udoprog Thanks! It may be worth saying in step’s docs something like: the returned optional is `None` until the receiver exits with a value. It wasn’t clear to me without reading and comprehending a a fair bit of code whether it’d be the `Some` for every expression, or each pushed stack frame, etc. I’m still not completely sure about yielding and other cases that behave like a return.
