### ISSUE TITLE
"Vm::call takes self by value, which means we're forced to clone()" - as per blog of 2020. What is the workaround or status as of year 2023?

### ISSUE THREAD

**Issue by zaxebo1** [rune-rs/rune#566]
In This comparison of all the rust embeddable scripting language 
https://www.boringcactus.com/2020/09/16/survey-of-rust-embeddable-scripting-languages.html
it says about "rune" disadvantage that:

>>   The one issue I notice is that Vm::call takes self by value, which means we're forced to clone() 
>> our VM every time we want to handle a new event instead of handling them all in the same VM. 
>> This probably means a more complicated script with some global state to maintain wouldn't be able 
>> to do that. So if that's something you know you'll want to support, Rune might not be for you, 
>> unless there's a different way to do this that I didn't find in the docs. But if you know you don't 
>> need that, Rune might work well for you.

Now as the above article is from year 2020. So I am curious that whether this limitation still exists in year 2023, and what is the workaround suggested.
Thanks in advance

**Comment by udoprog** [comment]
It now takes `&mut self`, so no workaround needed.

See: <https://docs.rs/rune/latest/rune/runtime/struct.Vm.html#method.call>.
