### ISSUE TITLE
Using a dedicated enum for the `Try` protocol

### ISSUE THREAD

**Issue by udoprog** [rune-rs/rune#590]
While looking over #587 I realized that I'm not a huge fan of the current return value for the `TRY` protocol.

To summarize, since the introduction of the `TRY` protocol (#544) it uses `Result` to indicate whether the short circuit or not. While this meshes well with the existing type system (`Value::Result` already exists and does basically what we want it to) it lacks clarity and becomes a bit messy with types such as `Result<T, Result<(), Error>>`.

Here I'm proposing we adopt the [`ControlFlow` enum](https://doc.rust-lang.org/std/ops/enum.ControlFlow.html) for this protocol.

Internally it also means that we should be able to represent it as a `Value` to the degree that at least the internal `Vm` operations are supported, which basically means conversion to and from `ControlFlow<Value, Value>`.

CC: @ModProg

**Comment by ModProg** [comment]
Makes sense, I used `Result` because it worked and already existed. I guess there is a reason std uses ControlFlow.

**Comment by udoprog** [comment]
To get an idea of how difficult it is to add support for an external enum, check out #591 where I've added `Value::Ordering`.
