### ISSUE TITLE
"halted for unexpected reason `awaited`" Error

### ISSUE THREAD

**Issue by physics515** [rune-rs/rune#595]
Hello all,

I can't seem to figure this one out. I'm trying to write an async function following the docs for 0.12 ([https://github.com/rune-rs/rune/blob/0.12.x/scripts/async.rn](https://github.com/rune-rs/rune/blob/0.12.x/scripts/async.rn)) and I get an error.

Function:
```
pub async fn scoped_test_script() { 
    let timeout = 200; 
    let request = http::get(`http://httpstat.us/200?sleep=${timeout}`); 
    let timeout = time::sleep(time::Duration::from_secs(2)); 
    let result = select { _ = timeout => timeout, res = request => res, }?; 
    result.text().await? 
}
```

Error on the `vm.call()` function:
```
halted for unexpected reason `awaited`
```

Context is:
```
let runtime_context: RuneContext = rune_modules::default_context().unwrap();
```

Any idea what I'm missing here?

Thanks!

**Comment by udoprog** [comment]
Hi! You have to use async variants of call / execution functions when running asynchronous code in Rune, like `async_call`: <https://docs.rs/rune/latest/rune/runtime/struct.Vm.html#method.async_call>.

**Comment by physics515** [comment]
@udoprog, I was able to figure that out but I'm stuck in another way. I'm building an app with Tauri and calling the VM from a Tauri Command.

I'm following this example: [https://github.com/rune-rs/rune/blob/0.12.x/examples/examples/tokio_spawn.rs](https://github.com/rune-rs/rune/blob/0.12.x/examples/examples/tokio_spawn.rs) but I keep running into an issue with the `Vm` not implementing `Send`. Do you know any way to fix this?

**Comment by udoprog** [comment]
Yeah, pass the `Arc<Unit>` and `Arc<RuntimeContext>` around, and construct a `Vm` (which is a cheap operation) when you need to execute something with `send_execute`.

**Comment by physics515** [comment]
But the error is on the `send_execute` call. I was looking into how Tauri does async and it appears their async implementation runs every await point on a new thread...? So that means `send_execute` is being run on a different thread than the other code, meaning it requires `Vm` to require a `Send` implementation.

I did try to spin up a new thread to get out of the Tauri runtime and run a generic tokio runtim, but I was trying to move the `Vm` into that thread. I'll try to pass the `Uint` and `Runtime` to the thread and create the `Vm` on the thread and see if that works.

I'll report back!

Thank you for your help.

**Comment by udoprog** [comment]
Note that `send_execute` returns a [`VmSendExecution`](https://docs.rs/rune/latest/rune/runtime/struct.VmSendExecution.html), which implements `Send` (but important not `Sync`!).

If you keep having issues, place put together a minimal reproduction and I might be able to help.

**Comment by physics515** [comment]
@udoprog, I figured out my issue. It is actually a Rust language bug where it doesn't `drop()` references correctly in async runtime.
[https://github.com/rust-lang/rust/issues/69663](https://github.com/rust-lang/rust/issues/69663) 

Instead of this:
``` rust
let vm = Vm::new(runtime, Arc::new(unit));
let execution = vm.clone().send_execute(["main"], (5u32,))?;
```

It should be this:
``` rust
let execution = {
    let vm = Vm::new(runtime, Arc::new(unit));
    vm.clone().send_execute(["main"], (5u32,))?;
};
```
So that `vm` is out of scope before the `await` in:
``` rust
execution.async_complete().await.unwrap();
```

or else there is a potential the `vm` will be moved to a new thread at the `await` point.

Thank you for your help! I hope this helps someone else.

**Comment by udoprog** [comment]
Glad to hear it. Note that you can do without the `.clone()` too since you're constructing a Vm for the call.
