### ISSUE TITLE
Function Pointers

### ISSUE THREAD

**Issue by vars1ty** [rune-rs/rune#644]
Is there any way of getting the memory address of a Rune function?
I have implemented Rune into a game mod I'm working on, and one of features I need requires the address of a function, as it's called dynamically via a library.

**Comment by udoprog** [comment]
Yeah, coerce it into a [`Function`](https://docs.rs/rune/latest/rune/runtime/struct.Function.html) and if you need that to be shared across threads a [`SyncFunction`](https://docs.rs/rune/latest/rune/runtime/struct.SyncFunction.html).

You can look up a function in the `Vm` using [`lookup_function`](https://docs.rs/rune/latest/rune/runtime/struct.Vm.html#method.lookup_function).
