### ISSUE TITLE
0.13.0 release build failure

### ISSUE THREAD

**Issue by chenrui333** [rune-rs/rune#645]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  error[E0433]: failed to resolve: unresolved import
     --> crates/rune/src/languageserver/state.rs:271:36
      |
  271 |         let Ok(formatted) = crate::fmt::layout_source(&source) else {
      |                                    ^^^
      |                                    |
      |                                    unresolved import
      |                                    help: a similar path exists: `core::fmt`
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6468976999/job/17562222470
relates to Homebrew/homebrew-core#150407

**Comment by udoprog** [comment]
Thanks!

Seems to be a feature unification issue when we only build with the `languageserver` feature.

I'm pushing a fix which tests that scenario in #646.

**Comment by udoprog** [comment]
0.13.1 is being shipped now, which hopefully contains a fix for this.

**Comment by chenrui333** [comment]
yeah, let me check now.

**Comment by chenrui333** [comment]
works for me, thanks!

**Comment by chenrui333** [comment]
@udoprog looks like the new tags did not get marked as releases, any reason why? Thanks!

![image](https://github.com/rune-rs/rune/assets/1580956/f0543e9b-0918-4fad-8aff-be22c71b73c8)

**Comment by udoprog** [comment]
Marking a release on Github is a manual process. I've done it now. Thanks!

**Comment by chenrui333** [comment]
Great, thanks a lot for doing it!
