### ISSUE TITLE
Documentation enhancements

### ISSUE THREAD

**Issue by Roba1993** [rune-rs/rune#648]
A list of all documentation enhancements/problems I noticed.
* The new generated rune documentation lacks a link to the module overview.
   * So when I'm at this [location](https://rune-rs.github.io/docs/json.module.html) there is no link to this [page](https://rune-rs.github.io/docs/).
* Too long source code is overflowing on the right side
   * <img width="977" alt="Bildschirmfoto 2023-10-30 um 09 38 20" src="https://github.com/rune-rs/rune/assets/1376958/f13fcc40-58c6-4ee6-a6f2-019694fbc484">
* When defining a module twice it's shown two times
   * e.g. When using io-nocapture and implement own dbg/print/println functions
   * Both links show the same content, but in this case the link with no comment should be hidden IMHO
   *  <img width="549" alt="Bildschirmfoto 2023-10-30 um 09 41 06" src="https://github.com/rune-rs/rune/assets/1376958/782b0586-b56e-49b0-ad47-7592d464d913">
* The ordering of the modules is random
   * <img width="112" alt="Bildschirmfoto 2023-10-30 um 09 42 18" src="https://github.com/rune-rs/rune/assets/1376958/3c844d29-e906-4005-b5b1-f24578028786">
* The display of protocol functions is not intuitive
   * Get / Set should have the field in the header to make it easier to read
      * <img width="309" alt="Bildschirmfoto 2023-10-30 um 09 44 56" src="https://github.com/rune-rs/rune/assets/1376958/e7f91d67-1201-420f-b738-d990269d629d">
* Field functions can be deprecated, when manually defined

**Comment by udoprog** [comment]
Closed in #677, cheers!
