### ISSUE TITLE
Error handling in built-in toml module

### ISSUE THREAD

**Issue by jasal82** [rune-rs/rune#656]
When I use the built-in toml module with invalid content and return its result in the script function, e.g.

```
pub fn main() {
  toml::from_string("[[broken]")
}
```

then I cannot dbg-print the `Value` that is returned by the execution. If I try something like

```
execution.complete().into_result();
match result {
    Ok(value) => {
        println!("{:?}", value);
    },
    Err(error) => { ... }
};
```

the program crashes with

```
panicked at library\std\src\io\stdio.rs:1019:9:
failed printing to stdout: formatter error
```

**Comment by jasal82** [comment]
When I dbg-print the value from within the script I get the expected output.

```
pub fn main() {
  dbg(toml::from_string("[[broken]"))
}
```

This prints

```
Err(Error { kind: SCANNER, problem: "found character that cannot start any token", context: "while scanning for the next token" })
```

**Comment by jasal82** [comment]
After adding the missing `toml::de::module()` and `toml::ser::module()` installations (which I guess should be added to the `toml::module()` function to make it self-contained) I can at least `dbg()` the error from within the script. However, I still cannot debug-print from Rust context.

**Comment by udoprog** [comment]
You'll have to put the call inside of a [`Vm::with`](https://docs.rs/rune/latest/rune/runtime/struct.Vm.html#method.with) since it might access vm internals. I think.

Assuming the error type implements string_debug.

Try it and report back!

**Comment by jasal82** [comment]
That was the problem. It works now. Thanks!
