### ISSUE TITLE
Missing docs for `#[rune::function(keep)]`

### ISSUE THREAD

**Issue by VorpalBlade** [rune-rs/rune#754]
I have been annoyed for a while that I can't call the Rune extension methods from Rust (when I need them from both locations). I was considering filing a feature request on this, but while looking through rune's own HashMap there is a `keep` attribute that seems to solve this nicely already.

But it is not documented in https://rune-rs.github.io/api/rune/attr.function.html

So: Is the docs missing (in which case I will make a PR) or is it an unstable private API (in which case I propose to stabilise it and document it)?

**Comment by udoprog** [comment]
It's just not documented for some reason, please fix!

**Comment by VorpalBlade** [comment]
Will do tomorrow
