### ISSUE TITLE
New 0.13.x release?

### ISSUE THREAD

**Issue by VorpalBlade** [rune-rs/rune#768]
I would (in the next week or so) appreciate a release or 0.13.x that includes 7ca25813c3c267148b4b0194332d4e0410a2213c:

* As far as I know there aren't any other (to me) criticial issues on 0.13.x before I can make a release of my project. (There are several things that would be nice-to-have, but nothing that I haven't already worked around or decided to live with, those can wait for 0.14)
* Apart from one (not related to rune) bug and the need to write docs I'm now at the point where I'm ready to publish the first 0.1.0 release of this konfigkoll project I have been working on. (That said, 0.2 will have a lot more feature that I have punted on, but I want to get this done and then take a break from it.)
* Since I'm publishing to crates.io, I can't keep using `[patch]`

**Comment by udoprog** [comment]
I've shipped `0.13.4`. Thanks!
