### ISSUE TITLE
Feature request: Raw string literals

### ISSUE THREAD

**Issue by VorpalBlade** [rune-rs/rune#802]
Rust has raw string literals using `#""#` syntax (with arbitrary but matching number of `#`). This is very handy when writing regular expressions. Consider adding support to Rune. Please, I'm going insane trying to use a regex to edit another regex in a file when I have to apply 4 layers of escaping.

Also this (not even a regex, just a replacement string, because I gave up trying to edit the one colour code of the original string with a regex, so I just replaced the entire line):

```rust
"    PS1='${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w \\$\\[\\033[00m\\] '"
```

So much escaping, I'm going to go take Alvedon now.

**Comment by VorpalBlade** [comment]
Oops, apparently dupe of #537 (I searched for "raw string literal" specifically, not just "raw", my bad)

**Comment by udoprog** [comment]
Closing as duplicate, thanks!
