### ISSUE TITLE
How to implement a simple trait

### ISSUE THREAD

**Issue by ramon-bernardo** [rune-rs/rune#821]
I've been looking at the trait example and its protocols, but it's not clear how to implement a trait. Could you provide me with an example?

```rust
// rust
pub trait Channel {
    fn on_join(&self, user: User);
}
```

```rust,rn
// rune
pub struct MyChannel;

impl Channel for MyChannel {
    pub fn on_join(self, user) {
        // ...
    }
}
```

**Comment by udoprog** [comment]
You can only build and implement traits in native modules, did you see [the new book section](https://rune-rs.github.io/book/traits.html)?
