### ISSUE TITLE
Customize Rune lint for VS Code

### ISSUE THREAD

**Issue by ramon-bernardo** [rune-rs/rune#822]
It would be interesting to customize Rune's lint for VS Code, similar to how Lua does it.

(https://marketplace.visualstudio.com/items?itemName=sumneko.lua)

```lua
---@alias os.mtime fun(): number

---@alias table.create fun(arrayLength: number, keyLength: number): table
---@alias table.pack fun(...): table

---@class rawgetmetatable
---@field __index fun(self: table, key: any): any
rawgetmetatable = {}```

**Comment by udoprog** [comment]
We don't have a type system yet even for diagnostics. This will become relevant once that is being worked on.

See #673
