### ISSUE TITLE
Vec::resize should clone elements being added

### ISSUE THREAD

**Issue by fujiehuang** [rune-rs/rune#858]
When the Vec.resize function is supplied with an empty vector as the initial value, all the slots seem to be sharing a same vector. Is this a bug? 

```rust
let a = [];
a.resize(3, []);
a[0].push(0);
a[1].push(1);
a[2].push(2);
dbg!(a);
// output: [[0, 1, 2], [0, 1, 2], [0, 1, 2]]
```

**Comment by udoprog** [comment]
Thanks for the report! This is a bug. `Vec::resize` should call `CLONE` on the values being added.
