### ISSUE TITLE
missing methods for VecDeque: is_empty(), clear()

### ISSUE THREAD

**Issue by fujiehuang** [rune-rs/rune#892]
these two methods are quite commonly used, and can be easily added:

diff --git a/crates/rune/src/modules/collections/vec_deque.rs b/crates/rune/src/modules/collections/vec_deque.rs
index 7a1ff37e..4cf517cd 100644
--- a/crates/rune/src/modules/collections/vec_deque.rs
+++ b/crates/rune/src/modules/collections/vec_deque.rs
@@ -29,6 +29,10 @@ pub fn module() -> Result<Module, ContextError> {
     m.function_meta(VecDeque::from_iter__meta)?;
     m.function_meta(VecDeque::reserve)?;
     m.function_meta(VecDeque::len)?;
+    
+    m.function_meta(VecDeque::is_empty)?;
+    m.function_meta(VecDeque::clear)?;
+
     m.function_meta(VecDeque::capacity)?;
     m.function_meta(VecDeque::front)?;
     m.function_meta(VecDeque::back)?;
@@ -311,6 +315,15 @@ impl VecDeque {
         self.inner.len()
     }
 
+    #[rune::function]
+    fn is_empty(&self) -> bool {
+        self.inner.is_empty()
+    }
+
+    #[rune::function]
+    fn clear(&mut self) {
+        self.inner.clear();
+    }
     /// Returns the number of elements the deque can hold without reallocating.
     ///

**Comment by udoprog** [comment]
I recommend opening up a pull request with the proposed code changes. Don't forget documentation!
