### ISSUE TITLE
Heads-up: #[start] is being removed

### ISSUE THREAD

**Issue by RalfJung** [rune-rs/rune#897]
We are planning to remove the unstable `#[start]` attribute from the compiler, see https://github.com/rust-lang/rust/pull/134299 for rationale and further details. This repo showed up in a search for users of the attribute in [this file](https://github.com/rune-rs/rune/blob/main/no-std/examples/minimal.rs). For all we know, there's no good reason to use this attribute and you can do the following instead:
```rust
#![no_main]

#[no_mangle]
extern "C" fn main(argc: core::ffi::c_int, argv: *const *const u8) -> core::ffi::c_int {
  // ...
}
```

If that for some reason does not work, please let us know!

**Comment by udoprog** [comment]
Thanks!
